/**
 * The background study tree: outline-derived sections whose summaries are
 * generated by the study model and cached against section-text hashes, plus a
 * whole-document abstract distilled from the finished summaries. Pure — the
 * queue that actually calls the model lives in state/study.svelte.ts, and the
 * reconcile/rescue mechanics deliberately mirror domain/narration.ts so the
 * two background layers age the same way.
 */
import { fnv64 } from './narration';
import type { LlmChatMessage } from '$lib/services/llm/llm-client';
import type { DocumentStudy, NormalizedDocument, OutlineEntry, StudyNode } from './types';

export const STUDY_PROMPT_VERSION = 1;

/** Hard ceiling on tree size: deepest outline levels drop first, so a
 * 400-heading textbook still yields a readable (and affordable) tree. */
export const STUDY_NODE_CAP = 40;

/** Per-section text budget sent to the model (~1,700 tokens). */
const SECTION_TEXT_CHARS = 7_000;

/** A section awaiting (or carrying) a summary: the unit of queue work. */
export interface StudySection {
	id: string;
	blockId: string;
	title: string;
	level: number;
	text: string;
	sourceHash: string;
}

function clampSectionText(text: string): string {
	const normalized = text.trim();
	if (normalized.length <= SECTION_TEXT_CHARS) return normalized;
	return `${normalized.slice(0, SECTION_TEXT_CHARS)} … (section continues)`;
}

/**
 * Derive the capped section list for a document. Sections partition the
 * segments in reading order: any lead content before the first heading
 * becomes an opening section titled after the document, and outline levels
 * deeper than the cap allows are folded into their parents.
 */
export function studySections(doc: NormalizedDocument, cap = STUDY_NODE_CAP): StudySection[] {
	const blockPositions = new Map(doc.blocks.map((block, index) => [block.id, index]));

	// Whether a candidate entry set leaves lead content needing its own node —
	// the cap must count that opening section too.
	const needsLead = (candidate: OutlineEntry[]): boolean => {
		const firstAt = candidate.length
			? (blockPositions.get(candidate[0].blockId) ?? 0)
			: doc.blocks.length;
		return doc.segments.some((segment) => {
			const at = blockPositions.get(segment.blockId);
			return at !== undefined && at < firstAt;
		});
	};

	// Deepest levels drop first until the tree fits the cap.
	const levels = [...new Set(doc.outline.map((entry) => entry.level))].sort((a, b) => a - b);
	let entries = doc.outline;
	for (let depth = levels.length; depth >= 1; depth -= 1) {
		const allowed = new Set(levels.slice(0, depth));
		entries = doc.outline.filter((entry) => allowed.has(entry.level));
		if (entries.length + (needsLead(entries) ? 1 : 0) <= cap) break;
	}
	const budget = cap - (needsLead(entries) ? 1 : 0);
	if (entries.length > budget) entries = entries.slice(0, Math.max(1, budget));

	interface Bound {
		id: string;
		blockId: string;
		title: string;
		level: number;
		from: number;
	}
	const bounds: Bound[] = [];
	// Lead content before the first heading is usually the document's most
	// important prose — it gets an opening section named after the document.
	if (needsLead(entries) || !entries.length) {
		bounds.push({
			id: 'study:lead',
			blockId: doc.blocks[0]?.id ?? 'lead',
			title: doc.title,
			level: 1,
			from: 0
		});
	}
	for (const entry of entries) {
		const from = blockPositions.get(entry.blockId);
		if (from === undefined) continue;
		bounds.push({
			id: `study:${entry.blockId}`,
			blockId: entry.blockId,
			title: entry.title,
			level: entry.level,
			from
		});
	}

	const sections: StudySection[] = [];
	for (let index = 0; index < bounds.length; index += 1) {
		const bound = bounds[index];
		const to = bounds[index + 1]?.from ?? doc.blocks.length;
		const parts: string[] = [];
		let previousBlockId: string | undefined;
		for (const segment of doc.segments) {
			const at = blockPositions.get(segment.blockId);
			if (at === undefined || at < bound.from || at >= to) continue;
			parts.push(segment.blockId === previousBlockId ? ` ${segment.text}` : `\n${segment.text}`);
			previousBlockId = segment.blockId;
		}
		const text = clampSectionText(parts.join(''));
		if (!text) continue;
		sections.push({
			id: bound.id,
			blockId: bound.blockId,
			title: bound.title,
			level: bound.level,
			text,
			sourceHash: fnv64(`${bound.title}\n${text}`)
		});
	}
	return sections;
}

export interface StudyReconciliation {
	study: DocumentStudy;
	queue: StudySection[];
	changed: boolean;
}

/** Hash of the ready summaries an abstract distills — stored on the study so
 * a changed tree re-queues the abstract. */
export function abstractSourceHash(nodes: StudyNode[]): string {
	return fnv64(
		nodes
			.filter((node) => node.status === 'ready' && node.summary)
			.map((node) => `${node.title}\n${node.summary}`)
			.join('\n\n')
	);
}

/**
 * Reconcile the derived sections against a stored study. Ready summaries
 * survive when their section hash still matches (by id, or rescued by
 * content hash after block-id shifts); everything else queues. The abstract
 * survives only while the ready summaries it distilled are unchanged.
 */
export function reconcileStudy(
	sections: StudySection[],
	existing: DocumentStudy | undefined
): StudyReconciliation {
	const previous = existing?.promptVersion === STUDY_PROMPT_VERSION ? existing : undefined;
	const byId = new Map((previous?.nodes ?? []).map((node) => [node.id, node]));
	const readyByHash = new Map<string, StudyNode>();
	for (const node of previous?.nodes ?? []) {
		if (node.status === 'ready' && node.summary) readyByHash.set(node.sourceHash, node);
	}

	const consumed = new Set<string>();
	const queue: StudySection[] = [];
	const nodes: StudyNode[] = sections.map((section) => {
		const exact = byId.get(section.id);
		if (exact && exact.sourceHash === section.sourceHash && exact.status === 'ready') {
			consumed.add(exact.id);
			return { ...exact, blockId: section.blockId, title: section.title, level: section.level };
		}
		const rescued = readyByHash.get(section.sourceHash);
		if (rescued && !consumed.has(rescued.id)) {
			consumed.add(rescued.id);
			return {
				...rescued,
				id: section.id,
				blockId: section.blockId,
				title: section.title,
				level: section.level
			};
		}
		queue.push(section);
		return {
			id: section.id,
			blockId: section.blockId,
			title: section.title,
			level: section.level,
			status: 'pending' as const,
			sourceHash: section.sourceHash,
			updatedAt: Date.now()
		};
	});

	const expectedAbstractHash = abstractSourceHash(nodes);
	const abstractIntact = Boolean(
		previous?.abstract &&
		previous.abstractStatus === 'ready' &&
		previous.abstractHash === expectedAbstractHash
	);

	const study: DocumentStudy = {
		nodes,
		...(abstractIntact
			? { abstract: previous?.abstract, abstractHash: previous?.abstractHash }
			: {}),
		abstractStatus: abstractIntact ? 'ready' : 'pending',
		modelId: previous?.modelId,
		promptVersion: STUDY_PROMPT_VERSION,
		updatedAt: Date.now()
	};

	const changed =
		!existing ||
		existing.promptVersion !== STUDY_PROMPT_VERSION ||
		existing.nodes.length !== nodes.length ||
		existing.nodes.some((node, index) => nodes[index] !== node) ||
		Boolean(existing.abstract) !== Boolean(study.abstract);

	return { study, queue, changed };
}

/** The abstract should regenerate once every node has settled and at least
 * one summary exists to distill. */
export function abstractNeeded(study: DocumentStudy): boolean {
	if (study.nodes.some((node) => node.status === 'pending')) return false;
	const ready = study.nodes.filter((node) => node.status === 'ready' && node.summary);
	if (!ready.length) return false;
	return study.abstractStatus !== 'ready' || study.abstractHash !== abstractSourceHash(study.nodes);
}

/* ── Prompts ─────────────────────────────────────────────────────────────── */

export function studySectionMessages(docTitle: string, section: StudySection): LlmChatMessage[] {
	return [
		{
			role: 'system',
			content:
				'You prepare concise study notes for a reading companion. Summarize the given ' +
				'section in two or three plain sentences: what it covers, and the one or two ideas ' +
				'a learner must retain. Write in the language of the section. No headings, no ' +
				'bullets, no preamble — only the sentences.'
		},
		{
			role: 'user',
			content: `Document: ${docTitle}\nSection: ${section.title}\n\n${section.text}`
		}
	];
}

export function studyAbstractMessages(docTitle: string, nodes: StudyNode[]): LlmChatMessage[] {
	const tree = nodes
		.filter((node) => node.status === 'ready' && node.summary)
		.map((node) => `${'  '.repeat(Math.max(0, node.level - 1))}- ${node.title}: ${node.summary}`)
		.join('\n');
	return [
		{
			role: 'system',
			content:
				'You prepare a one-paragraph abstract of a document from its section notes. Write ' +
				'three to five plain sentences in the language of the notes: what the document is ' +
				'about, how it unfolds, and what a reader gets from it. No meta-commentary.'
		},
		{ role: 'user', content: `Document: ${docTitle}\n\nSection notes:\n${tree}` }
	];
}

/* ── Assistant instruction block ─────────────────────────────────────────── */

/**
 * Serialize the study layer for the assistant's session instructions: the
 * abstract plus an indented tree of section notes, each tagged with the
 * section's first ⟦n⟧ marker so the model can show or tour from it. Empty
 * string when nothing useful is ready yet.
 */
export function composeStudyBlock(doc: NormalizedDocument): string {
	const study = doc.study;
	if (!study) return '';
	const ready = study.nodes.filter((node) => node.status === 'ready' && node.summary);
	if (!study.abstract && !ready.length) return '';
	const firstSegmentByBlock = new Map<string, number>();
	doc.segments.forEach((segment, index) => {
		if (!firstSegmentByBlock.has(segment.blockId)) firstSegmentByBlock.set(segment.blockId, index);
	});
	const lines: string[] = [];
	if (study.abstract) lines.push(`Abstract: ${study.abstract}`);
	if (ready.length) {
		if (lines.length) lines.push('');
		lines.push('Section notes:');
		for (const node of ready) {
			const indent = '  '.repeat(Math.max(0, node.level - 1));
			const at = firstSegmentByBlock.get(node.blockId);
			const marker = at === undefined ? '' : `⟦${at}⟧ `;
			lines.push(`${indent}- ${marker}${node.title} — ${node.summary}`);
		}
	}
	return lines.join('\n');
}
